# specify auto shutdown on finish: oncomplete on success or failure, onsuccess for success
# only, onfailure for failure only, never for no auto shutdown
shutdown: oncomplete
samples:
  mode: dir
  sampledir: upload
  samplelist: samples.txt
  sampleaccess: accession.txt
sampledir: upload